version: "3"

services:
    mysql:
        image: mysql:5.6
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=lakeexclusive
            - MYSQL_USER=lake
            - MYSQL_PASSWORD=password
        restart: unless-stopped

    app:
        build:
            args:
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        environment:
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
